### ISSUE TITLE
Not able to run the tests

### ISSUE THREAD

**Issue by gautam-sharma1** [dfki-ric/movement_primitives#42]
I am trying to run the tests. I have installed the repo using:

1. Cloning the repo
2. Running python3 -m pip install -e ".[all]" 

I also install tests dependencies using:

1. python3 -m pip install -e ".[test]"

When I run the test command highlighted in the README, I get the following error: 

gautamsharma@MacBook-Pro-3 movement_primitives % python3 -m nose test
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/lib/python3.11/site-packages/nose/__main__.py", line 8, in <module>
    run_exit()
  File "/opt/homebrew/lib/python3.11/site-packages/nose/core.py", line 118, in __init__
    unittest.TestProgram.__init__(
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/main.py", line 101, in __init__
    self.parseArgs(argv)
  File "/opt/homebrew/lib/python3.11/site-packages/nose/core.py", line 179, in parseArgs
    self.createTests()
  File "/opt/homebrew/lib/python3.11/site-packages/nose/core.py", line 193, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/nose/loader.py", line 481, in loadTestsFromNames
    return unittest.TestLoader.loadTestsFromNames(self, names, module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/nose/loader.py", line 454, in loadTestsFromName
    return LazySuite(
           ^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/nose/suite.py", line 53, in __init__
    super(LazySuite, self).__init__()
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/suite.py", line 22, in __init__
    self._tests = []
    ^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/nose/suite.py", line 106, in _set_tests
    if isinstance(tests, collections.Callable) and not is_suite:
                         ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Callable'

My system info as follows:

gautamsharma@MacBook-Pro-3 movement_primitives % system_profiler SPHardwareDataType                                   
**Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,3
      Model Number: MKGQ3LL/A
      Chip: Apple M1 Pro
      Total Number of Cores: 10 (8 performance and 2 efficiency)
      Memory: 16 GB
      System Firmware Version: 10151.81.1
      OS Loader Version: 10151.81.1
      Serial Number (system): M2J4FMXJJM
      Hardware UUID: 9E39F940-63A8-50ED-AC31-7FB37BB65822
      Provisioning UDID: 00006000-001A21C91121801E
      Activation Lock Status: Enabled**

**Comment by AlexanderFabisch** [comment]
Thanks for reporting. It seems like nosetest is broken in Python 3.11. We will have to switch to pytest.

**Comment by AlexanderFabisch** [comment]
@gautam-sharma1 I opened a PR that replaces nose by pytest: #43 . Could you confirm that it works? Then I will merge it to main.

**Comment by gautam-sharma1** [comment]
It works now. Thank you!
